#detects if the system is 32 or 64 bits
BITS_OPTION = -m64

#### defines the compiler
CPPC = g++
#############################

#### compilation options and includes
CCOPT = $(BITS_OPTION) -O3 -fPIC -fexceptions -DNDEBUG -DIL_STD -std=c++0x
CONCERTINCDIR = $(CONCERTDIR)/include
#############################

#### linker flags
#############################

#### directories with source files and object files
SRCDIR = src
OBJDIR = obj
#############################

#### list of all source files and all object files
SRCS = $(wildcard $(SRCDIR)/*.cpp)
OBJS = $(patsubst $(SRCDIR)/%.cpp, $(OBJDIR)/%.o, $(SRCS))
#############################

#### main rule, generates the executable
mlp: $(OBJS) 
	@echo  "\033[31m \nLinking all objects files: \033[0m"
	$(CPPC) $(BITS_OPTION) $(OBJS) -o $@ $(CCLNFLAGS)
############################

#includes the dependency files
-include $(OBJS:.o=.d)

#rule for each object file: compiles and generates the dependency file for the object file
#each object file depends on the .c and the headers (header info is in the dependency file generated by the compiler)
$(OBJDIR)/%.o: $(SRCDIR)/%.cpp
	@echo  "\033[31m \nCompiling $<: \033[0m"
	$(CPPC) $(CCFLAGS) $(CCOPT) -c $< -o $@
	@echo  "\033[32m \ncreating $< dependency file: \033[0m"
	$(CPPC) -std=c++0x  -MM $< > $(basename $@).d
	@mv -f $(basename $@).d $(basename $@).d.tmp #next three lines add the directory to the dependency file (g++ does not add it, surprisingly!)
	@sed -e 's|.*:|$(basename $@).o:|' < $(basename $@).d.tmp > $(basename $@).d
	@rm -f $(basename $@).d.tmp

#delete object and dependency files
clean:
	@echo "\033[31mcleaning obj directory \033[0m"
	@rm mlp -f $(OBJDIR)/*.o $(OBJDIR)/*.d


rebuild: clean tsp

